project/admin/views.py
import csv

from flask import Blueprint, render_template, request, flash, redirect, url_for, send_from_directory, send_file
from flask_login import login_user, current_user, login_required, logout_user
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import text

from project.models.models import User, Datasource, ReportSource
from project import db


admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/', methods=['GET', 'POST'])
def home():
    return redirect('/admin')


@admin_blueprint.route('/admin/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')


        if User.verify_hash(password, current_user.password):
            current_user.authenticated = True
            db.session.add(current_user)
            db.session.commit()
            login_user(current_user)

            return redirect(url_for('admin.dashboard'))
        else:
            db.session.rollback()
            flash('ERROR! Incorrect login credentials.', 'error')

    return render_template('login.html')


@admin_blueprint.route('/admin/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    return redirect(url_for('admin.login'))


@admin_blueprint.route('/admin/')
# @login_required
def dashboard():
    return render_template('dashboard.html')


# USERS ############################################
@admin_blueprint.route('/admin/users')
# @login_required
def users():
    all_user = User.query.all()
    return render_template('users.html', users=all_user)


@admin_blueprint.route('/admin/user_add', methods=['GET', 'POST'])
# @login_required
def user_add():
    if request.method == 'POST':
        try:
            username = request.form.get('username')
            password = User.generate_hash(request.form.get('password'))
            is_admin = request.form.get('is-admin')
            if is_admin:
                new_user = User(username, password, role='admin')
            else:
                new_user = User(username, password)

            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('admin.users'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR! username ({}) already exists.'.format(username), 'error')

    return render_template('user_add.html')


@admin_blueprint.route('/admin/user_delete/<user_id>')
# @login_required
def user_delete(user_id):
    user = User.find_by_id(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('admin.users'))


@admin_blueprint.route('/admin/user_edit/<user_id>', methods=['GET', 'POST'])
# @login_required
def user_edit(user_id):
    user = User.find_by_id(user_id)
    if request.method == 'POST':
        try:
            is_admin = request.form.get('is-admin')
            # password = request.form.get('password')

            user.username = request.form.get('username')
            # user.password = User.generate_hash(password)
            # if User.verify_hash(password, current_user.password):
            #     user.password = password

            user.address = request.form.get('address')
            if is_admin:
                user.role = 'admin'

            db.session.commit()
            return redirect(url_for('admin.users'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR! username ({}) already exists.'.format(user.username), 'error')

    return render_template('user_edit.html', user=user)

# Data Source ####################################################
@admin_blueprint.route('/admin/datasources')
# @login_required
def datasources():
    allsource = Datasource.query.all()
    return render_template('datasources.html', datasources=allsource)

@admin_blueprint.route('/admin/datasource_add', methods=['GET', 'POST'])
# @login_required
def datasource_add():
    if request.method == 'POST':
        try:
            site_name = request.form.get('site_name')
            site_url = request.form.get('site_url')

            new_datasource = Datasource(site_name, site_url)

            db.session.add(new_datasource)
            db.session.commit()
            return redirect(url_for('admin.datasources'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR!')

    return render_template('datasource_add.html')


@admin_blueprint.route('/admin/datasource_delete/<datasource_id>')
# @login_required
def datasource_delete(datasource_id):
    datasource = Datasource.find_by_id(datasource_id)
    db.session.delete(datasource)
    db.session.commit()
    return redirect(url_for('admin.datasources'))


@admin_blueprint.route('/admin/datasource_edit/<datasource_id>', methods=['GET', 'POST'])
# @login_required
def datasource_edit(datasource_id):
    datasource = Datasource.find_by_id(datasource_id)
    if request.method == 'POST':
        try:
            datasource.site_name = request.form.get('site_name')
            datasource.site_url = request.form.get('site_url')

            db.session.commit()
            return redirect(url_for('admin.datasources'))

        except IntegrityError:
            db.session.rollback()
            flash('ERROR!')

    return render_template('datasource_edit.html', datasource=datasource)

# Report Source ####################################################
@admin_blueprint.route('/admin/reportsource')
# @login_required
def reportsources():
    allreport = ReportSource.query.all()
    return render_template('reportsources.html', reportsources=allreport)

@admin_blueprint.route('/admin/export_reportsources')
def export_reportsources():
    # Use this format if using pandas
    # Cars = {'Brand': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
    #         'Price': [22000, 25000, 27000, 35000]
    #         }
    # df = DataFrame(datas, columns=datas.keys())
    # df.to_csv('data_desa.csv', index=None, header=True)

    all_report = db.session.execute(text(
        'SELECT kode_pos, desa, kode, kecamatan, dt2, kota, provinsi FROM reportsource'
    ))
    c = csv.writer(open('project/static/file/report.csv', 'w+'))
    c.writerow(['kode_pos', 'desa', 'kode', 'kecamatan', 'dt2', 'kota', 'provinsi'])
    for x in all_report:
        c.writerow(x)

    return redirect('/file/report.csv')


@admin_blueprint.route('/admin/reportsource_delete/<reportsource_id>')
# @login_required
def reportsource_delete(reportsource_id):
    reportsource = ReportSource.find_by_id(reportsource_id)
    db.session.delete(reportsource)
    db.session.commit()
    return redirect(url_for('admin.reportsources'))

project/admin/templates/_form_macros.html
{% macro render_field(field) %}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="error">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
  </dd>
{% endmacro %}

project/admin/templates/allert_message.html
{% for error_message in get_flashed_messages(category_filter=["error"]) %}
  <div class="alert alert-danger alert-dismissible text-center">{{ error_message }}</div>
{% endfor %}

{% for success_message in get_flashed_messages(category_filter=["success"]) %}
  <div class="alert alert-success alert-dismissible text-center">{{ success_message }}</div>
{% endfor %}

{% for info_message in get_flashed_messages(category_filter=["info"]) %}
  <div class="alert alert-info alert-dismissible text-center">{{ info_message }}</div>
{% endfor %}

project/admin/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
    Dashboard
{% endblock %}


{% block body %}
    {% include 'header.html' %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-ctn">
										<h2>Welcome in Village Scraper</h2>
										<strong><i>Scraping all village in Indonesia</i></strong>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->

    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/datasource_add.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Datasource Add
{% endblock %}

{% block body %}
    {% include 'header.html' %}
    {% include 'allert_message.html' %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									</div>
									<div class="breadcomb-ctn">
										<h2>Datasource</h2>
										<a href="{{ url_for('admin.datasource_add') }}">Create</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->


    <div class="container">
         <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap">
                        <form action="{{ url_for('admin.datasource_add') }}" method="post">
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Site name</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="Site name"  name="site_name">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15">
                                <div class="form-group">
                                    <label>Site URL</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="Site URL"  name="site_url">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15">
                                <button class="btn btn-success notika-btn-success">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>

    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/datasource_edit.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Datasource Edit
{% endblock %}

{% block body %}
    {% include 'header.html' %}
    {% include 'allert_message.html' %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Data source</h2>
										<a href="{{ url_for('admin.datasource_add') }}">Create</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->


    <div class="container">
         <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap">
                        <form action="{{ url_for('admin.datasource_edit', datasource_id=datasource.id) }}" method="post">
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Site Name</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{datasource.site_name}}"  name="site_name" value="{{datasource.site_name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15">
                                <div class="form-group">
                                    <label>Site URL</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{datasource.site_url}}"  name="site_url" value="{{datasource.site_url}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15">
                                <button class="btn btn-success notika-btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>




    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/datasources.html
{% extends "base.html" %}

{% block title %}
    Data sources
{% endblock %}


{% block body %}
    {% include 'header.html' %}
    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Data sources</h2>
										<a href="{{ url_for('admin.datasource_add') }}">Create</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->

    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Site name</th>
                                        <th>Site URL</th>
                                         <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for source in datasources %}
                                    <tr class="odd gradeX">
                                        <td>{{ source.site_name }}</td>
                                        <td>{{ source.site_url }}</td>
                                        <td>
                                            <a href="{{ url_for('admin.datasource_delete', datasource_id=source.id) }}">Delete</a>
                                            ||
                                            <a href="{{ url_for('admin.datasource_edit', datasource_id=source.id) }}">Edit</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/header.html
<!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- Start Header Top Area -->
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo-area">
                        <a href="#"><img src="{{ url_for('static',filename='img/logo/logo.png') }}" alt="" /></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="header-top-menu">
                        <ul class="nav navbar-nav notika-top-nav">
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span><i class="notika-icon notika-search"></i></span></a>
                                <div role="menu" class="dropdown-menu search-dd animated flipInX">
                                    <div class="search-input">
                                        <i class="notika-icon notika-left-arrow"></i>
                                        <input type="text" />
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item"><a href="{{ url_for('admin.logout') }}" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span><i class="notika-icon notika-close"></i></span></a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Top Area -->
    <!-- Mobile Menu start -->
    <div class="mobile-menu-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="mobile-menu">
                        <nav id="dropdown">
                            <ul class="mobile-menu-nav">
                                <li><a href="{{ url_for('admin.dashboard') }}">Home</a></li>
                                <li><a href="{{ url_for('admin.users') }}">User Data</a></li>
                                <li><a href="{{ url_for('admin.datasources') }}">Data source</a></li>
                                <li><a href="{{ url_for('admin.reportsources') }}">Report source</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Mobile Menu end -->
    <!-- Main Menu area start-->
    <div class="main-menu-area mg-tb-40">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="nav nav-tabs notika-menu-wrap menu-it-icon-pro">
                        <li><a href="{{ url_for('admin.dashboard') }}"><i class="notika-icon notika-house"></i> Home</a></li>
                        <li><a href="{{ url_for('admin.users') }}"><i class="notika-icon notika-avable"></i> User Data</a></li>
                        <li><a href="{{ url_for('admin.datasources') }}"><i class="notika-icon notika-windows"></i> Data source</a></li>
                        <li><a href="{{ url_for('admin.reportsources') }}"><i class="notika-icon notika-draft"></i> Report source</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Menu area End-->

project/admin/templates/reportsources.html
{% extends "base.html" %}

{% block title %}
    Report sources
{% endblock %}


{% block body %}
    {% include 'header.html' %}
    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>Report sources</h2>
                                        <i>Data founds:  {{ reportsources|length }}</i> ||
<!--                                        <a href="{{ url_for('static',filename='file/report.csv') }}" download>Download csv</a>-->
                                            <a href="{{ url_for('admin.export_reportsources') }}" download>Download csv</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->

    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Data sources</th>
                                        <th>Kode pos</th>
                                        <th>Desa / Kelurahan</th>
                                        <th>Kode wilayah</th>
                                        <th>Kecamatan / Distrik</th>
                                        <th>DT2</th>
                                        <th>Kabupaten / Kota</th>
                                        <th>Provinsi</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for report in reportsources %}
                                    <tr class="odd gradeX">
                                        <td>{{ report.data_source }}</td>
                                        <td>{{ report.kode_pos }}</td>
                                        <td>{{ report.desa }}</td>
                                        <td>{{ report.kode }}</td>
                                        <td>{{ report.kecamatan }}</td>
                                        <td>{{ report.dt2 }}</td>
                                        <td>{{ report.kota }}</td>
                                        <td>{{ report.provinsi }}</td>
                                        <td>
                                            <a href="{{ url_for('admin.reportsource_delete', reportsource_id=report.id) }}">Delete</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/user_edit.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block title %}
    Users
{% endblock %}

{% block body %}
    {% include 'header.html' %}
    {% include 'allert_message.html' %}

    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>User Data</h2>
										<a href="{{ url_for('admin.user_add') }}">Create</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->


    <div class="container">
         <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-example-wrap">
                        <form action="{{ url_for('admin.user_edit', user_id=user.id) }}" method="post">
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Username</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{user.username}}"  name="username" value="{{user.username}}">
                                    </div>
                                </div>
                            </div>
<!--                            <div class="form-example-int mg-t-15">-->
<!--                                <div class="form-group">-->
<!--                                    <label>Password</label>-->
<!--                                    <div class="nk-int-st">-->
<!--                                        <input type="password" class="form-control input-sm" placeholder="{{ user.password }}"  name="password" value="{{user.password}}">-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Address</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{user.address}}"  name="address" value="{{user.address}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Bank</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{user.bank_name}}"  name="bank-name" value="{{user.bank_name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int">
                                <div class="form-group">
                                    <label>Nomor rekening</label>
                                    <div class="nk-int-st">
                                        <input type="text" class="form-control input-sm" placeholder="{{user.bank_number}}" name="bank-number" value="{{user.bank_number}}">
                                    </div>
                                </div>
                            </div>
                             <div class="form-example-int mg-t-15">
                                <div class="form-group">
                                    <div class="nk-int-st">
                                         <label>Admin ?</label> <input type="checkbox" name="is-admin"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-example-int mg-t-15">
                                <button class="btn btn-success notika-btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
    </div>




    {% include 'footer.html' %}
{% endblock %}

project/admin/templates/users.html
{% extends "base.html" %}

{% block title %}
    Users
{% endblock %}


{% block body %}
    {% include 'header.html' %}
    <!-- Breadcomb area Start-->
	<div class="breadcomb-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="breadcomb-list">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="breadcomb-wp">
									<div class="breadcomb-icon">
										<i class="notika-icon notika-windows"></i>
									</div>
									<div class="breadcomb-ctn">
										<h2>User Data</h2>
										<a href="{{ url_for('admin.user_add') }}">Create</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Breadcomb area End-->

    <!-- Data Table area Start-->
    <div class="data-table-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="data-table-list">
                        <div class="table-responsive">
                            <table id="data-table-basic" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Username</th>
                                        <th>Address</th>
                                        <th>Date Registered</th>
                                        <th>Role</th>
                                        <th>Nama bank</th>
                                        <th>Nomor rekening</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for user in users %}
                                    <tr class="odd gradeX">
                                        <td>{{ user.username }}</td>
                                        <td>{{ user.address }}</td>
                                        <td>{{ user.register_on }}</td>
                                        <td>{{ user.role }}</td>
                                        <td>{{ user.bank_name }}</td>
                                        <td>{{ user.bank_number }}</td>
                                        <td>
                                            <a href="{{ url_for('admin.user_delete', user_id=user.id) }}">Delete</a>
                                            ||
                                            <a href="{{ url_for('admin.user_edit', user_id=user.id) }}">Edit</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Data Table area End-->
    {% include 'footer.html' %}
{% endblock %}